<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div>
        <h2>Профиль: </h2>
    </div>

    <div>
        <ul>
        <li><a>Вклады</a></li>
        <li><a>Страхование</a></li>
        <li><a>Ипотека</a></li>
        <li><a href="/credit">Кредит - количество кредитов:</a></li>
        <li><a>Вклады</a></li>
        </ul>
    </div>

    <div>
        <h3>Кошелёк</h3>
        <h5>Some numbers to case</h5>
    </div>
</body>
</html>